config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin_events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: :index
  resources :moneys, only: :update
  resources :admin_moneys, only: [:edit, :update]
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/money.rb
class Money < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_events_controller.rb
class AdminEventsController < ApplicationController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /admin_events
  # GET /admin_events.json
  def index
    @admin_events = Event.order(:date)
    @money = Money.first
  end

  # GET /admin_events/1
  # GET /admin_events/1.json
  def show
  end

  # GET /admin_events/new
  def new
    @admin_event = Event.new
  end

  # GET /admin_events/1/edit
  def edit
  end

  # POST /admin_events
  # POST /admin_events.json
  def create
    @admin_event = Event.new(admin_event_params)
    if @admin_event.save
      redirect_to admin_events_url, notice: 'Admin event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin_events/1
  # PATCH/PUT /admin_events/1.json
  def update
    if @admin_event.update(admin_event_params)
      redirect_to admin_events_url, notice: 'Admin event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin_events/1
  # DELETE /admin_events/1.json
  def destroy
    @admin_event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Admin event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_event_params
      params.require(:event).permit(:date, :location, :location_url, :time, :ticket_url, :details)
    end
end

app/controllers/admin_moneys_controller.rb
class AdminMoneysController < ApplicationController

  def edit
    @money = Money.first
  end

  def update
    @money = Money.first
    @money.dollar = money_params[:dollar]
    if @money.save
      redirect_to admin_events_path
    else
      render :edit
    end
  end

  private

  def money_params
    params.require(:money).permit(:dollar)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    admin_events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @first         = Event.where("date = ''").first
    @second        = Event.where("date = 'Every Monday in April with Brooklyn Caravan 7:00-9:00'").first
    @horse         = Event.where("date = '5/6'").first
    @events        = Event.where("date != '' AND date != 'Every Monday in April with Brooklyn Caravan 7:00-9:00' AND date != '5/6'").sort_by{|x| x.date.to_date}
    needed         = 65000.00
    raised         = Money.find_by(name: 'Amount Raised')
    percent        = (raised.dollar/needed) * 100
    @amount_needed = "$65,000"
    @amount_raised = raised.dollar
    @goal_percent  = "#{percent.to_i}%"
  end

end

app/controllers/moneys_controller.rb
class MoneysController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update]

  def update
    m = Money.find(params[:id])
    amount = moneys_params[:amount].to_f
    m.dollar += amount
    m.save
  end

  private

  def moneys_params
    params.require(:donate).permit(:amount)
  end
end

app/helpers/admin_events_helper.rb
module AdminEventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moneys_helper.rb
module MoneysHelper
end

app/views/admin_events/edit.html.haml
%h1 Editing admin_event

= form_for @admin_event, url: "/admin_events/#{@admin_event.id}", method: 'put' do |f|
  - if @admin_event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_event.errors.count, "error")} prohibited this admin_event from being saved:"
      %ul
        - @admin_event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :location_url
    = f.text_field :location_url
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :details
    = f.text_field :details
  .actions
    = f.submit 'Save'



= link_to 'Back', admin_events_path

app/views/admin_events/index.html.haml
%h1 Listing admin_events

.row
  .col-md-2
    %h2
      Date
  .col-md-2
    %h2
      Location
  .col-md-2
    %h2
      Time
  .col-md-2
    %h2
      Details
  .col-md-2
  .col-md-2

.row
  .col-md-12
    - @admin_events.each do |admin_event|
      .row
        .col-md-2
          %h4
            = admin_event.date
        .col-md-2
          %h4
            = admin_event.location
        .col-md-2
          %h4
            = admin_event.time
        .col-md-2
          %h4
            = admin_event.details
        .col-md-2
          %h4
            = link_to 'Edit', edit_admin_event_path(admin_event)
        .col-md-2
          %h4
            = link_to 'Destroy', admin_event_path(admin_event), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
.row
  .col-md-4.col-md-offset-1
    %p
      = link_to 'New Admin event', new_admin_event_path
.row
  .col-md-4.col-md-offset-1
    %p
      = "Amount Raised: #{@money.dollar}"
    %p
      = link_to 'Edit Amount Raised', edit_admin_money_path(@money)

app/views/admin_events/new.html.haml
%h1 New admin_event

= form_for @admin_event, url: '/admin_events' do |f|
  - if @admin_event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_event.errors.count, "error")} prohibited this admin_event from being saved:"
      %ul
        - @admin_event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :location_url
    = f.text_field :location_url
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :details
    = f.text_field :details
  .actions
    = f.submit 'Save'


= link_to 'Back', admin_events_path

app/views/admin_events/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @admin_event.date
%p
  %b Location:
  = @admin_event.location
%p
  %b Location url:
  = @admin_event.location_url
%p
  %b Time:
  = @admin_event.time
%p
  %b Ticket url:
  = @admin_event.ticket_url
%p
  %b Details:
  = @admin_event.details

= link_to 'Edit', edit_admin_event_path(@admin_event)
\|
= link_to 'Back', admin_events_path

app/views/admin_moneys/edit.html.haml
.row
  .col-md-4.col-md-offset-4.text-center
    %h4
      = "Amount Currently Raised: #{@money.dollar}"

.row
  .col-md-4.col-md-offset-4.text-center
    %h4 Below, enter the new current amount raised.
.row
  .col-md-4.col-md-offset-4
    = form_for @money, url: "/admin_moneys/#{@money.id}", method: 'put' do |f|
      = f.text_field :dollar
      = f.submit 'Update'

app/views/events/index.html.haml
.container
  .header-image
    .row
      .col-md-8.col-md-offset-2
        = image_tag("sunnyslogo.png", id: 'logo')
    .row
      .col-md-8.col-md-offset-2
        %p.description.text-center There are one-of-a-kinds in this world. Sunny's Bar is one of them. After a long uphill battle since Superstorm Sandy, this old Brooklyn Institution is ready to plan a long future. The good news is that we have banks onboard to give us the mortgage, but since we had to agree to pay a lot more than we initially thought for the building, we need help beefing up the downpayment. Invest in good spirit, and help secure good times for years and years to come!!!
        %p.description.text-center Don't let the sun go down on this Brooklyn community institution! SUNNY'S FOREVER is a campaign to secure the future of the what the New York Times called "the glorious dive, music hall, art gallery and oddball hangout on the waterfront in Red Hook." Sunny’s Bar, Revived After Hurricane Sandy, Is Being Saved, Again - New York Times, January 2017
  #money-meter
    %h3.text-center.money-text
      = "So far we have raised $#{number_with_delimiter(@amount_raised.to_i)} out of #{@amount_needed}"
    .row
      .col-md-6.col-md-offset-3
        .progress
          .progress-bar.progress-bar-success.progress-bar-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: #{@goal_percent}; min-width: 3em;"}
            %span
              = "$#{@amount_raised.to_i}"
  %main#events
    .row
      .col-md-6.col-md-offset-3.text-center
        %h1 EVENTS
    .row
      .col-md-6.col-md-offset-3.text-center
        %h2#monday_event Starting in April, Sunny's will be open every Monday at 4:00 PM with Live Jazz starting at 7:00 PM and a Signature Cocktail!
    -# .row.horse-race
    -#   .col-md-8.col-md-offset-2
    -#     .col-md-1
    -#       %h3
    -#         = @horse.date
    -#     .col-md-3
    -#       %h3
    -#         %a{:href => "#{@horse.location_url}"}
    -#           = @horse.location
    -#     .col-md-2
    -#       %h3
    -#         %a{:href => "#{@horse.ticket_url}" } Get Tickets
    -#     .col-md-2
    -#       %h3
    -#         = @horse.time
    -#     .col-md-4
    -#       %h3
    -#         = @horse.details
    .row
      .col-md-8.col-md-offset-2
        .row.hidden-sm.hidden-xs
          .col-md-2
            %h3.column-heads
              Date
          .col-md-4
            %h3.column-heads
              Location
          .col-md-2
            %h3.column-heads
              Time
          .col-md-4
            %h3.column-heads
              Details
        .row.event
          .col-md-2
            = ''
          .col-md-4
            %h4
              -if @first && @first.location
                = @first.location
          .col-md-2
            %h4
              = ''
          .col-md-4
            %h5
              -if @first && @first.details
                = @first.details
        .row.event
          .col-md-2
            = ''
          .col-md-4
            %h4
              -if @second && @second.location
                = @second.date
          .col-md-2
            %h4
              -# = @second.time
          .col-md-4
            %h5
              -if @second && @second.details
                = @second.details
        - @events.each do |event|
          .row.event
            .col-md-2
              %h4
                -if event && event.date
                  = event.date
            .col-md-4
              %h4
                -if event && event.location && event.location_url
                  %a{:href => "#{event.location_url}"}
                    = event.location
            .col-md-2
              %h4
                -if event && event.time
                  = event.time
            .col-md-4
              %h5
                -if event && event.details
                  = event.details
  #donate
    .row
      .col-md-6.col-md-offset-3.text-center
        %h3 Can't make it to one of our great events? Donate here!
    .row
      .col-md-6.col-md-offset-3.text-center
        %h3 Via Venmo
    .row
      .col-md-2.col-sm-2.col-xs-2.col-md-offset-4.col-sm-offset-4
        = text_field_tag :amount, '$', class: 'form-control', id: 'donate-field'
      .col-md-2.col-sm-2.col-xs-2
        %a#donate-button.btn.btn-primary{:href => "https://venmo.com/?txn=pay&audience=friends&recipients=SunnysforeverRedhook"} Donate!
    .row
      .col-md-6.col-md-offset-3.text-center
        %h3 By Mail
    .row
      .col-md-6.col-md-offset-3.text-center
        %h4 Mail Donations To:
        %h4 253 Conover Street, Brooklyn, NY 11231
  .footer
    .row
      .col-md-6.pull-left
        %a{:href => "http://johnmaguiredeveloper.com/"} &copy; John Maguire Designs
      .col-md-1.pull-right
        %a{:href => "https://www.facebook.com/sunnysredhook/"}
          %i.fa.fa-facebook-square.fa-3x{"aria-hidden" => "true"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SunnysForever
    = csrf_meta_tags
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://use.fontawesome.com/5919a198db.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield